name: "Bump version"

on:
  push:
    branches:
      - "master"
    paths-ignore:
      - "package.json"
      - "CHANGELOG.md"
jobs:
  bump-version:
    name: "Bump Version on master"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.BUMP_VERSION_ACTION_TOKEN }}
      - name: "Bump version and push tag"
        uses: TriPSs/conventional-changelog-action@master
        with:
          github-token: ${{ secrets.BUMP_VERSION_ACTION_TOKEN }}
          git-message: "ci: version bump to {version}"
          preset: "angular"
          output-file: "CHANGELOG.md"
