name: CI / Bump version
on:
  pull_request:
    branches:
      - master
    types: [closed]
jobs:
  bump:
    if: github.event.pull_request.merged == true
    name: "Bump Version"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          token: ${{ secrets.BUMP_VERSION_ACTION_TOKEN }}
          fetch-depth: 0
      - name: "Bump version"
        uses: Wawa27/automatic-version-bump@1.0.0
